In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [67]:
data=pd.read_csv('C:/Coding Blocks-Assignments/Movie Prediction No deep Leaning/Train.csv')

In [68]:
data

review label
0      mature intelligent and highly charged melodram...   pos
1      http://video.google.com/videoplay?docid=211772...   pos
2      Title: Opera (1987) Director: Dario Argento Ca...   pos
3      I think a lot of people just wrote this off as...   pos
4      This is a story of two dogs and a cat looking ...   pos
5      Steve Carell comes into his own in his first s...   pos
6      I'm only going to write more because it's requ...   neg
7      OK, it was a "risky" move to rent this flick, ...   neg
8      Cannibalism, a pair of cinematic references to...   pos
9      This is one of the great modern kung fu films....   pos
10     Steve Martin looks like he's had a face lift. ...   neg
11     Robert Jordan is a television star. Robert Jor...   pos
12     Probably the best comedy in a long time. keeps...   pos
13     The earlier review is pretty much on target, w...   neg
14     It is depressing that many people don't unders...   pos
15     This, like Murder She Wrote, is one of those s...   pos
16     This film is a sleeper because Rod Steiger's i...   pos
17     Give director Stanley Tong of Jackie Chan's Su...   neg
18     This is another of my favorite Columbos. It sp...   pos
19     This film IS brilliant...... without a doubt. ...   pos
20     "Soul Plane" is a horrible attempt at comedy t...   neg
21     "Party Girl" capitalizes on the tremendous cha...   pos
22     I haven't seen so many people packed outside a...   pos
23     Kevin Spacey is without a doubt one of the bes...   neg
24     i love this film!! maybe it is my generation b...   pos
25     The first time I saw this film I was a kid. I ...   pos
26     This movie is simply awesome. It is so hilario...   pos
27     This movie was horrible. I swear they didn't e...   neg
28     Two things can happen when an ensemble cast is...   pos
29     This is such a revered and studied film, a cla...   pos
...                                                  ...   ...
39970  Best animated movie ever made. This film explo...   pos
39971  I thought the whole movie played out beautiful...   pos
39972  Trot out every stereotype and misrepresentatio...   neg
39973  I saw Chan Is Missing when it first came out, ...   neg
39974  "There are some things you just don't do" so s...   neg
39975  This film is essentially for those who have ha...   pos
39976  I was all ready to pan this episode, seeing th...   pos
39977  When I first viewed this movie, I didn't know ...   neg
39978  A large bed possessed by a demon eats people, ...   pos
39979  When is ART going to overcome racism? I believ...   pos
39980  Since I am not a big Steven Seagal fan, I thou...   neg
39981  This movie seems to send the wrong message. Th...   neg
39982  MEN OF HONOR features Cuba Gooding Jr., in wha...   pos
39983  Houseboat Horror is a great title for this fil...   neg
39984  A documentary filmmaker explores seemingly unr...   pos
39985  I love this movie, Jouvet, Arletty, Blier, Car...   pos
39986  I rented Dark Harvest (the first one) because ...   neg
39987  In what must be one of the most blood-freezing...   pos
39988  This is my favorite of the three care bears mo...   pos
39989  I'd read about FLAVIA THE HERETIC for many yea...   pos
39990  In the year 2006, "In Cold Blood"-a riveting t...   pos
39991  The creators of south park in their own film h...   pos
39992  This movie has lots of action and little heart...   neg
39993  Jude Law, Nicole Kidman, and Renne Zelwigger. ...   neg
39994  This was a great movie! Even though there was ...   pos
39995  There are similarities between Ray Lawrence's ...   neg
39996  For starters, I once met the director when he ...   neg
39997  Much of "Over Her Dead Body" is so painfully u...   neg
39998  "Lifeforce" is a truly bizarre adaptation of t...   pos
39999  I saw this movie at a screener and its the bes...   pos

[40000 rows x 2 columns]

In [69]:
X=data.iloc[:,0]

In [70]:
y=data.iloc[:,1]

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [73]:
from sklearn.preprocessing import LabelEncoder

In [74]:
lb=LabelEncoder()

In [75]:
y_train=lb.fit_transform(y_train)

In [138]:
lb.

array(['neg', 'pos'], dtype=object)

In [76]:
from sklearn.feature_extraction.text import CountVectorizer

In [77]:
cv=CountVectorizer(max_features=5000)

In [78]:
X_train_vec=cv.fit_transform(X_train)

In [79]:
X_train_vec.shape

(28000, 5000)

In [80]:
from sklearn.feature_extraction.text import TfidfTransformer

In [81]:
tf=TfidfTransformer()

In [82]:
X_train_tf=tf.fit_transform(X_train_vec)

In [83]:
type(X_train_tf)

scipy.sparse.csr.csr_matrix

In [84]:
from sklearn.linear_model import LogisticRegression

In [85]:
lr=LogisticRegression()

In [86]:
lr.fit(X_train_tf,y_train)

C:\Users\Pcv\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [87]:
X_test_vec2=cv.transform(X_test)

In [90]:
X_test_vec2.shape

(12000, 5000)

In [91]:
X_test_tf=tf.transform(X_test_vec2)

In [93]:
u=lr.predict(X_test_tf)

In [94]:
u

array([1, 1, 1, ..., 0, 1, 0])

In [95]:
from sklearn.metrics import confusion_matrix

In [99]:
confusion_matrix(u,y_test)

array([[5219,  623],
       [ 727, 5431]], dtype=int64)

In [98]:
y_test=lb.fit_transform(y_test)

In [108]:
test_data=pd.read_csv('C:/Coding Blocks-Assignments/Movie Prediction No deep Leaning/Test.csv')

In [109]:
test_data.shape

(10000, 1)

In [110]:
test_data=test_data.values

In [112]:
test_data=test_data.reshape((10000,))

In [113]:
test_data.shape

(10000,)

In [114]:
test_data_vec=cv.transform(test_data)

In [115]:
test_data_vec.shape

(10000, 5000)

In [116]:
test_data_tf=tf.transform(test_data_vec)

In [141]:
r=lr.predict(test_data_tf)

In [142]:
r.shape

(10000,)

In [143]:
r

array([0, 0, 0, ..., 1, 1, 0])

In [122]:
import csv

In [144]:
for i in range(0,10000):
    if r[i]==0:
        r[i]=25434
    else:
        r[i]=25435
    data=[i,r[i]]
    with open('C:/Coding Blocks-Assignments/Movie Prediction No deep Leaning/result4.csv','a',newline='') as f:
        writer=csv.writer(f)
        writer.writerows([data])